apiVersion: v1
kind: Service
metadata:
  namespace: spring-petclinic
  labels:
    app: api-gateway
  name: api-gateway
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: api-gateway
