apiVersion: v1
kind: Service
metadata:
  namespace: spring-petclinic
  labels:
    app: customers-service
  name: customers-service
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
  selector:
    app: customers-service
