apiVersion: v1
kind: Service
metadata:
  namespace: spring-petclinic
  labels:
    app: discovery-server
  name: discovery-server
spec:
  ports:
    - name: "8761"
      port: 8761
      targetPort: 8761
  selector:
    app: discovery-server
