apiVersion: v1
kind: Service
metadata:
  namespace: spring-petclinic
  labels:
    app: visits-service
  name: visits-service
spec:
  ports:
    - name: "8082"
      port: 8082
      targetPort: 8082
  selector:
    app: visits-service
