apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vets-service-ingress
  namespace: spring-petclinic
  annotations:
    kubernetes.io/ingress.class: "azure/application-gateway"
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/api/vet/"
        backend:
          service:
            name: vets-service
            port:
              number: 8083
