apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: spring-petclinic
  name: vets-service-ingress
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
  labels:
    app: vets-service
spec:
  rules:
  - http:
      paths:
      - pathType: ImplementationSpecific
        path: /api/vet(/|$)(.*)
        backend:
          service:
            name: vets-service
            port:
              number: 8083

