apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: visits-service-ingress
  namespace: spring-petclinic
  annotations:
    kubernetes.io/ingress.class: "azure/application-gateway"
spec:
  rules:
  - host: petclinic.com
    http:
      paths:
      - pathType: Prefix
        path: "/api/visit/"
        backend:
          service:
            name: visits-service
            port:
              number: 8082
