apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: spring-petclinic
  name: visits-service-ingress
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
  labels:
    app: visits-service
spec:
  rules:
  - http:
      paths:
      - pathType: ImplementationSpecific
        path: /api/visit(/|$)(.*)
        backend:
          service:
            name: visits-service
            port:
              number: 8082
