apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: visits-service-ingress
  namespace: spring-petclinic
spec:
  ingressClassName: "azure-application-gateway"
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/api/visit/"
        backend:
          service:
            name: visits-service
            port:
              number: 8082
